name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v2 

      - name: Deploy to Server
        uses: fanggong/rsync-deploy@main
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }} 
          ARGS: -avz --delete
          SERVER_PORT: "22"
          FOLDER: ./
          SERVER_IP: ${{ secrets.SSH_HOST }} 
          USERNAME: ${{ secrets.SSH_USERNAME }} 
          SERVER_DESTINATION: /srv/feishu/

      - name: Update environment
        uses: fanggong/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            # conda env update -f /srv/feishu/environment.yml
            cp /root/config.yml /srv/feishu/config.yml
            # cd /srv/feishu
            # chmod +x deploy.sh
            # ./deploy.sh